# Generated by Django 5.0.4 on 2024-05-21 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DadosProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.localidades')),
            ],
        ),
    ]
