# Generated by Django 5.0.4 on 2024-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosprodutos',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
